#!/bin/bash

SONG_URI="https://open.spotify.com/track/0zv6iIwVr3J9SftqWPQpJn?si=0Zr1wvC2QXyywzJakkxwvw&context=spotify%3Aplaylist%3A37i9dQZF1EJCaqygKn39WE"

# Spotify playback loop
function start_spotify_loop() {
  while true; do
    spotify --one-shot $SONG_URI
  done
}

# Call the function to start the loop
start_spotify_loop
